language:
  - scala
jdk:
  - oraclejdk8
scala:
  - 2.12.8
branches:
  only:
    - master
before_install:
  - nvm install 6
  - node --version
  - npm --version
install:
  - npm install -g serverless
script:
  - sbt assembly
after_script:
  - serverless deploy -v
