language:
- scala
jdk:
- oraclejdk8
scala:
- 2.12.8
env:
  global:
  - secure: u50bo4exMDZwMQ7FDHEVWlEVzdagx0JGYAHx8geMNDb7EplneD5eEnmgL7HfLUDNxxCWhPBnQPbG13jq4c/4eXSQdzMe67z0Zd+KklZA35QvpPCdUbuOjwl3vIHrEQDtyaIKw2O6w7aVTd8JhMVf8STdK+nBcFAAtPBGD4zQ1XbYN4J/gPaMd9mV4VbVxGxPGUR+4q35wranyG7F0hE0vHxa4DWLuLYofEZjoAT3fDF3TSpWmnkCeD+JBrmtpOxA7vShYsWsJrK94qX1p/jt9+/E4TsEqQ9KuaMHB+i0tKaovx233imT5enMpdtEVjy0V24VkSjFtm6EqprGPIozmSFQyt1RT7fNTHZolZAs+9i0jOhBhLabdkAPuU8NMYajJGFSkvzMzQPkserJ7AU43tUAoP6h6N1QqiHs4Er9+hn09EpwRkLQPoFYhufV2sxQSaCykXkFbVgcSYHdqGGaFHIo/0u9rholtJfp8VJV7NhtBj/xKdFUbF1lsjbiLzdxnMm/taswvvxtu6tZnM2PamzVn9iqdtjJAe91LDMCt2d50N6f+RsiAFVm+r8HAmXJ51iXIoLstmOgjrHtDs+CVe4Fmk8+yIdBOe5MdAWwUlJ5fbccPon1HNYUbpMWq4Qb87yiNuI2yBau2HeBkr6+xhnTUrzW0UOgeuU7meXwx0U=
  - secure: H0s0lVRg7ffQTQyIsfTRwie+Y0fwu663pgjfQ68GRXzYW7eSANkVqz+RwNoi2huf+WKHFdMHUcug7MnHrZMi/B74Y6dczsAjlcoT6a4NW5yhNiZDWVsAzfSrGZi8EpBms8Xi+pcFvNHJLJlSOPlwNkm2/BKpruvzjhkZnnhJZxeqq9+VJ51sQ9kzhfyzZsmTTbyM9SnDZtGGjB/JiVFFR2G5CTPNEEyolWg4m6JILh8YXNaXaCmk7OWlXIVoudoqKDJo5cgY3WpxepoigrH9jorvfrUQlXZ1cAKUN7IKarHve5ily2ZanPIFyuX0+hn4dtYk0pFGSxXUim0yCMyr2UNiD6q+oa55mIFeOONqRDkX4nA0CURgMgYJqgT+rSIP7yGH7Im3fTHx+rcGno/39A3Xl+jO5ykSuEbFgkoYsNP+brbKqKis2I+YwHZKWMyoDCUj/tcsLtkVmJmJvzmY05fpp9AEgTJ97esodfzamoFXIJ1CDzLBwD+dV9/PXeEvMZFScTWFH32jjCEGbF7GaSeRr7BWyB/+ychznIr3SBKVvrKmbIlUlLnbgGCpXvhG0bmX/IlzmZuevBFFT1cXRbA/Ouyv+ryvvlXxOpNLRYGIiJ1mKwpj2nD+6tAA/rR3Gf0T0gzt041YB1EcnRU8UsACdBBKkweHg8C2P7R1u6I=
branches: 
only:
- master
before_install:
- nvm install $NODE_VERSION
- node --version
- npm --version
install:
- npm install -g serverless
script:
- sbt assembly
after_script:
- serverless deploy -v
