service: my-scala-lambda

provider:
  name: aws
  runtime: java8

package:
  artifact: target/scala-2.12/hello.jar

functions:
  hello:
    handler: hello.ApiGatewayHandler
    events:
      - http:
          path: users
          method: get
